name: Generate PlantUML Diagrams
on:
  push:
    paths:
      - "**.puml"
  pull_request:
    branches:
      - master
    paths:
      - "**.puml"

jobs:
  plantuml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Generate SVG Diagrams
        uses: holowinski/plantuml-github-action@main
        with:
          args: -v -tsvg diagrams/*.puml
